### PR TITLE
Ui clientmanagement rank branch tally

### PR DESCRIPTION
**Pull request by wcampbell09**

### CODE REVIEW

**Review by AriTheGuitarMan — DISMISSED** [review]
I like the additional of the branch and rank functionalities. Going strong my friend.

**Review by eristow — APPROVED** [review]
thank sneak boi

**Review by angryoctopode — APPROVED** [review]
Who would win, this merge, or one conflicty boi?

**Review by dkwhite200 — APPROVED** [review]

**Review by AriTheGuitarMan — APPROVED** [review]
I approve this message.

**Pull request merged**
