### PR TITLE
Merge move_multi_items into dev_sprint3

### PR DESCRIPTION
**Pull request by angryoctopode**
Code that allows user to move a certain quantity of an item all at once

### CODE REVIEW

**Comment by eristow** [comment]
This doesn't also allow movement of multiple UPCs to multiple clients, right?

**Comment by angryoctopode** [comment]
Yeah, Im still working on that, but its on its own branch. I just wanted to get this working first and figured it was ready to go.

**Review by eristow — APPROVED** [review]
Gotcha. Approved

**Review by AriTheGuitarMan — APPROVED** [review]
Very good upgrade. As you said you are still working on it, I concur with your current changes. I Think it would be a useful and great addition to our sprint 3 progress.

**Pull request closed without merging**
