### PR TITLE
Merge Move inventory functions into dev2_sprint2

### PR DESCRIPTION
**Pull request by angryoctopode**

### CODE REVIEW

**Review by eristow — APPROVED** [review]
good job boy

**Review by wcampbell09 — APPROVED** [review]
Toasty looks good

**Review by AriTheGuitarMan — APPROVED** [review]
I like the addition of snackbar, styles, toasts, move functionality, and implementation. Goode.

**Review by dkwhite200 — APPROVED** [review]
f i r e

**Pull request merged**
