### PR TITLE
Header Updated: Back button removed; commented out code removed

### PR DESCRIPTION
**Pull request by dkwhite200**

### CODE REVIEW

**Review by eristow — DISMISSED** [review]
good stuff

**Review by wcampbell09 — DISMISSED** [review]
looks good

**Review by AriTheGuitarMan — DISMISSED** [review]

**Review by angryoctopode — APPROVED** [review]
Noice, 11/10

**Review by eristow — APPROVED** [review]
still good, my friend

**Review by wcampbell09 — APPROVED** [review]
iz good

**Pull request merged**
