### PR TITLE
Merge Client details inventory to dev2_sprint2

### PR DESCRIPTION
**Pull request by angryoctopode**

### CODE REVIEW

**Review by wcampbell09 — APPROVED** [review]
looks good 2 me

**Review by eristow — APPROVED** [review]
Good job, friend.

**Review by dkwhite200 — APPROVED** [review]

**Review by AriTheGuitarMan — APPROVED** [review]
Makes sense. The table inventory commit makes sense.

**Review by angryoctopode — COMMENTED** [review]
Looks good to me

**Pull request merged**
