### PR TITLE
Working client roles checkboxes. Bug Terminated.

### PR DESCRIPTION
**Pull request by AriTheGuitarMan**
Client roles checkboxes works. Minor bug fixed. I kept the fix very minimal to avoid merge conflicts with all of our other work. It is good to merge.

### CODE REVIEW

**Review by dkwhite200 — CHANGES_REQUESTED** [review]
Hey Ari. I was looking at the controler for client management and I think the changeStatus_____ () functions are unnecessary. Would it be a good idea to cut them out and add them onto this branch to clean up code?

**Comment by AriTheGuitarMan** [comment]
I am positive that the changeStatus was of use to someone else throughout the process of the code. If I am wrong, then I will remove it nonetheless.

**Comment by dkwhite200** [comment]
No like the changeStatusStaff(), changeStatusVolunteer.... those functions are unnecessary. Def remove those before pulling in. I already tested the program after removing them and it works fine.

**Comment by AriTheGuitarMan** [comment]
I see your point. Sounds good.

**Comment by AriTheGuitarMan** [comment]
I have also fixed the client management views and added a more appealing touch to them.

**Review by eristow — DISMISSED** [review]
Everything looks good and runs correctly.

**Review by dkwhite200 — DISMISSED** [review]

**Review by dkwhite200 — DISMISSED** [review]

**Review by dkwhite200 — APPROVED** [review]

**Comment by AriTheGuitarMan** [comment]
Tested it a lot and it works amazingly.

**Pull request merged**
